import {
  Home,
  Heart,
  User,
  Settings,
  Search,
  Star,
  Flame,
  Dumbbell,
  Activity,
  BarChart3,
  Check,
  X,
  ArrowLeft,
  ArrowRight,
  Plus,
  Minus,
  Bell,
  Mail,
  Camera,
  Image,
  Edit,
  Trash2,
  Share2,
  Download,
  Upload,
  Lock,
  Unlock,
  Eye,
  Clock,
  Calendar,
  MapPin,
  Phone,
  Globe,
  Zap,
  Shield,
  Award,
  Target,
  TrendingUp,
  Bookmark,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  MoreHorizontal,
  MoreVertical,
  Menu,
  LogOut,
  LogIn,
  CreditCard,
  ShoppingCart,
  Package,
  Gift,
  Coffee,
  Music,
  Play,
  Pause,
  Square,
  Circle,
  Info,
  AlertTriangle,
  AlertCircle,
  CheckCircle,
  XCircle,
  HelpCircle,
  MessageCircle,
  Send,
  Layers,
  Grid,
  List,
  Filter,
  Sliders,
  RefreshCw,
  ExternalLink,
  Link,
  Paperclip,
  FileText,
  Folder,
  Copy,
  Clipboard,
  Tag,
  Hash,
  AtSign,
  Wifi,
  Battery,
  Smartphone,
  Monitor,
  Printer,
  Speaker,
  Headphones,
  Mic,
  Video,
  Film,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Thermometer,
  Umbrella,
  Wind,
  Compass,
  Navigation,
  Map,
  Flag,
  Crosshair,
  Users,
  UserPlus,
  UserCheck,
} from 'lucide-react';

const iconMap = {
  'home': Home,
  'heart': Heart,
  'user': User,
  'settings': Settings,
  'search': Search,
  'star': Star,
  'flame': Flame,
  'dumbbell': Dumbbell,
  'activity': Activity,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'check': Check,
  'x': X,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'plus': Plus,
  'minus': Minus,
  'bell': Bell,
  'mail': Mail,
  'camera': Camera,
  'image': Image,
  'edit': Edit,
  'trash': Trash2,
  'trash-2': Trash2,
  'share': Share2,
  'share-2': Share2,
  'download': Download,
  'upload': Upload,
  'lock': Lock,
  'unlock': Unlock,
  'eye': Eye,
  'clock': Clock,
  'calendar': Calendar,
  'map-pin': MapPin,
  'phone': Phone,
  'globe': Globe,
  'zap': Zap,
  'shield': Shield,
  'award': Award,
  'target': Target,
  'trending-up': TrendingUp,
  'bookmark': Bookmark,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'menu': Menu,
  'log-out': LogOut,
  'log-in': LogIn,
  'credit-card': CreditCard,
  'shopping-cart': ShoppingCart,
  'package': Package,
  'gift': Gift,
  'coffee': Coffee,
  'music': Music,
  'play': Play,
  'pause': Pause,
  'square': Square,
  'circle': Circle,
  'info': Info,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'help-circle': HelpCircle,
  'message-circle': MessageCircle,
  'send': Send,
  'layers': Layers,
  'grid': Grid,
  'list': List,
  'filter': Filter,
  'sliders': Sliders,
  'refresh-cw': RefreshCw,
  'external-link': ExternalLink,
  'link': Link,
  'paperclip': Paperclip,
  'file-text': FileText,
  'folder': Folder,
  'copy': Copy,
  'clipboard': Clipboard,
  'tag': Tag,
  'hash': Hash,
  'at-sign': AtSign,
  'wifi': Wifi,
  'battery': Battery,
  'smartphone': Smartphone,
  'monitor': Monitor,
  'printer': Printer,
  'speaker': Speaker,
  'headphones': Headphones,
  'mic': Mic,
  'video': Video,
  'film': Film,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'thermometer': Thermometer,
  'umbrella': Umbrella,
  'wind': Wind,
  'compass': Compass,
  'navigation': Navigation,
  'map': Map,
  'flag': Flag,
  'crosshair': Crosshair,
  'users': Users,
  'user-plus': UserPlus,
  'user-check': UserCheck,
};

export function getIcon(name) {
  if (!name) return null;
  const key = name.toLowerCase().trim();
  return iconMap[key] || null;
}

export default iconMap;
